### ISSUE TITLE
Build fails on NEXUS_URL

### ISSUE THREAD

**Issue by szedjani** [decisionbrain/cplex-scala#2]
I tried to build the new release, but it fails as the build.gradle refers to an environmental variable called NEXUS_URL. I don't have this set up and based on the comments it should be a library developed also by DecisionBrain and one comment even refers to it as nexus.decisionbrain.loc, but I guess it's a domain only used internally.

**Comment by danielgodard** [comment]
Thanks for reporting this issue. I confirm, this URL is for our internal use only. Sorry about this.

Here is a work-around:

1/ Add the following lines in the file `build.gradle` after the `apply` statements for instance:

>     ext {
>        if (!project.hasProperty('NEXUS_URL'))
>            NEXUS_URL = "None"
>        if (!project.hasProperty('MAVEN_USER'))
>            MAVEN_USER= "None"
>        if (!project.hasProperty('MAVEN_PASSWORD'))
>            MAVEN_PASSWORD = "None"
>     }
> 
>     println("Nexus URL: $NEXUS_URL")
>     println("Maven user: $MAVEN_USER")

2/ Remove the following lines in the section `repositories` in file build.gradle:

>     maven {
>         credentials {
>             username "$MAVEN_USER"
>             password "$MAVEN_PASSWORD"
>         }
>         url "$NEXUS_URL/repository/public"
>     }
 
You should then be able to build the library again.

**Comment by szedjani** [comment]
Yep, it helped. Thank you.

Also, it's a bit confusing what to libraries import in my own project alongside the cplex-scala library to make it work. So with version 1.3 and 1.4 I had to import oplall.jar and its binaries to make the model run, but with this version, I shall import cplex.jar and its binaries instead of oplall. (So now it works, but it is worth mentioning in the README.)

**Comment by danielgodard** [comment]
Yes, correct. I had to do this due to issues with IloIntSet: this class has
different and incompatible implementation in oplall.jar, cplex.jar and
ILOG.CP.jar.

Daniel

--

Daniel Godard
Co-founder, VP Analytics Solution Factory
24 rue Louis Blanc
75010 Paris
www.decisionbrain.com

**Comment by danielgodard** [comment]
FYI, I have just release a hotfix 1.5.2 with the above changes.

Daniel
